### ISSUE TITLE
Cannot use target-stitch with taps-fixerio due to conflicting "requests" versions

### ISSUE THREAD

**Issue by stengland** [singer-io/target-stitch#10]
Hi, we are trying to send fixerio data to stitch but it looks like libraries require different versions of `requests` so we are getting this error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 654, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 859, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.12.4 (/usr/lib/python3.5/site-packages), Requirement.parse('requests==2.13.0'), {'tap-fixerio'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/tap-fixerio", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 656, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 669, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests==2.13.0' distribution was not found and is required by tap-fixerio
usage: target-stitch [-h] [-c CONFIG] [-n]
```

I'm afraid I am no expert on Python/Pip version management. Is there any way around this?

Thanks

**Comment by stengland** [comment]
A bit of extra context. We are running inside a docker container.

```
FROM iron/python:3

RUN python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --upgrade pip setuptools && \
    rm -r /root/.cache

RUN pip install target-stitch tap-fixerio
COPY ./sing.sh .

ENTRYPOINT ["sh", "sing.sh"]
```

`sing.sh`
```
tap-fixerio --config $CONFIG_FILE | target-stitch --config $CONFIG_FILE
```

**Comment by KAllan357** [comment]
@stengland, this is an issue discussed https://github.com/singer-io/getting-started/pull/21 and https://github.com/singer-io/getting-started/issues/19. 

What you can do is use `virtualenv` to setup two separate python environments and pipe the commands together like you are already doing.

**Comment by stengland** [comment]
@KAllan357 Excellent thanks. I will take a look at that and hopefully that will solve the issue.
