### ISSUE TITLE
pip install errors when tap-okta is installed

### ISSUE THREAD

**Issue by rshah-amplify** [singer-io/target-stitch#84]
Building wheels for collected packages: target-stitch, singer-python, psutil, cchardet, ciso8601, pycparser
  Building wheel for target-stitch (setup.py) ... done
  Stored in directory: /Users/rshah/Library/Caches/pip/wheels/63/dc/04/be88939a22c4d88504c433cc884c281406b982ffdae3f40668
  Building wheel for singer-python (setup.py) ... done
  Stored in directory: /Users/rshah/Library/Caches/pip/wheels/2b/35/d5/35e8fae6d940e7bfa591011adc823ee208b3751a652c53e9d7
  Building wheel for psutil (setup.py) ... done
  Stored in directory: /Users/rshah/Library/Caches/pip/wheels/22/64/5c/7857809363751351134f8f421f1c3d9d626b598700efd993c5
  Building wheel for cchardet (setup.py) ... done
  Stored in directory: /Users/rshah/Library/Caches/pip/wheels/45/bd/59/127f79612a869d1437e28dc8dedceb64dc8d2599cb1c905910
  Building wheel for ciso8601 (setup.py) ... done
  Stored in directory: /Users/rshah/Library/Caches/pip/wheels/ee/6c/3b/14af41fa8b2b4831b927528e505e06181927e3b97b0a7f7b36
  Building wheel for pycparser (setup.py) ... done
  Stored in directory: /Users/rshah/Library/Caches/pip/wheels/8f/8d/16/66a4dbccaa7bafcd29b8690eebaf45b2f387aa67570a0ce1e6
Successfully built target-stitch singer-python psutil cchardet ciso8601 pycparser
ERROR: tap-okta 0.0.5 has requirement singer-python==5.6.0, but you'll have singer-python 5.8.0 which is incompatible.
Installing collected packages: pbr, mock, backoff, ciso8601, singer-python, psutil, async-timeout, multidict, yarl, attrs, aiohttp, cchardet, pycparser, cffi, pycares, aiodns, target-stitch
  Found existing installation: backoff 1.3.2
    Uninstalling backoff-1.3.2:
      Successfully uninstalled backoff-1.3.2
  Found existing installation: singer-python 5.6.0
    Uninstalling singer-python-5.6.0:
      Successfully uninstalled singer-python-5.6.0
Successfully installed aiodns-2.0.0 aiohttp-3.5.4 async-timeout-3.0.1 attrs-19.3.0 backoff-1.8.0 cchardet-2.1.4 cffi-1.13.2 ciso8601-2.1.2 mock-2.0.0 multidict-4.7.4 pbr-5.4.4 psutil-5.3.1 pycares-3.1.1 pycparser-2.19 singer-python-5.8.0 target-stitch-3.0.2 yarl-1.4.2
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 11, in <module>
    load_entry_point('pip==19.1.1', 'console_scripts', 'pip3')()
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/__init__.py", line 78, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 227, in main
    timeout=min(5, options.timeout)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 92, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/download.py", line 380, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/download.py", line 160, in user_agent
    setuptools_version = get_installed_version("setuptools")
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 889, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 567, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 623, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1974, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1414, in has_metadata
    return self._has(path)
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1845, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1722, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1679, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/backoff-1.3.2-py3.7.egg'

**Comment by dmosorast** [comment]
This is addressed in the [getting started guide](https://github.com/singer-io/getting-started/blob/master/docs/FAQ.md#how-do-i-prevent-dependency-conflicts-between-my-tap-and-target). We recommend to run taps and targets in separate virtual environments.
